name: Build Crionic Core Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    env:
      PREFIX: ${{ github.workspace }}/depends/x86_64-w64-mingw32
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils curl git wget python3
          sudo apt-get install -y libboost-system-dev libboost-filesystem-dev libboost-chrono1.65-dev libboost-program-options-dev libboost-thread-dev
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:luke-jr/bitcoincore
          sudo apt-get update
          sudo apt-get -y install libdb4.8-dev libdb4.8++-dev libminiupnpc-dev libqrencode-dev
          sudo apt-get -y install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
          sudo apt install -y g++-mingw-w64-x86-64
          sudo update-alternatives --config x86_64-w64-mingw32-g++ 
          PATH=$(echo "$PATH" | sed -e 's/:/mnt.*//g') # strip out problematic Windows %PATH% imported var
          

      - name: Setup cross-compile environment
        run: |
          export CC=x86_64-w64-mingw32-gcc
          export CXX=x86_64-w64-mingw32-g++
          export PATH=$PREFIX/bin:$PATH

      - name: Build depends
        run: |
          cd depends
          make HOST=x86_64-w64-mingw32 -j$(nproc)
          cd ..

      - name: Run autogen
        run: ./autogen.sh

      - name: Configure Crionic Core
        run: |
          ./configure --disable-bench --disable-tests --disable-zmq \
                      --prefix=$PREFIX \
                      --host=x86_64-w64-mingw32 \
                      CC=x86_64-w64-mingw32-gcc \
                      CXX=x86_64-w64-mingw32-g++ \
                      BDB_INCLUDE_PATH=$PREFIX/include \
                      BDB_LIB_PATH=$PREFIX/lib

      - name: Build Crionic Core
        run: |
          make -j$(nproc)

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: crionic-win64
          path: |
            src/qt/release/*.exe
            src/qt/release/*.dll
